/* Azure Devops
Object ID
cc6a965c-e80a-4d78-8dc5-b3220faf566f
Storage account - pwstrgrrde857
# Azure Devops claud take care of our Project execution
1.create the free account in microsoft azure by providing all info
2. on dashboard cloct 3 dots -> create resource-> search for 'playwright workspace' -> click
-> provide all info -> create ->goto azure dashboard-> click 3dots ->az login get started -> follow the steps to integrate our local workspace
 to azure workspace as follows
 ru Cmds in PW terminal

 1. install PW service package - npm init @azure/playwright@latest 
  when we run above cmd in project playwright.service.config.js file is generated by using which 
  we do execution in azure cloud

 2. download and install - azure cli
 get the ids from azure account
object id - cc6a965c-e80a-4d78-8dc5-b3220faf566f
Storage account id - pwstrgrrde857
run following cmds to setup local workspace to azure workspace
 3. Login to azure using azure cli - run cmd -  az login
 
4. $env:PLAYWRIGHT_SERVICE_URL="wss://eastus.api.playwright.microsoft.com/playwrightworkspaces/68cec135-967f-41a0-9c72-1be0d04c01c4/browsers"

5  Get the resource ID and store it in a variable
$storageId = az storage account show --name pwstrgrrde857 --resource-group rrd --query id -o tsv

# 6. Run the role assignment using the variable
az role assignment create `
   --assignee "cc6a965c-e80a-4d78-8dc5-b3220faf566f" `
   --role "Storage Blob Data Contributor" `
   --scope \$storageId

   7.use cmd to cloud execution - npx playwright test --config=playwright.service.config.ts --workers=20

   8. When we run above cmd then execution will happen in azure cloud. we can login to azureaccount 
   goto tests run we can see all info like logs ,reports so  we can shre the that browser link of report to team 
   also we 

   9. we can also configure above cmd in jenkins and schedule the job/execution.
   so we can see all info by login to azure acc.


   ***********Push Local code to Github repo for cicd demo************

   1. Login to Github acc
   2. create new Repo
   3. Downlod and install git in local system
   4. Goto project derectory and open cmd prompt
   5. run cmd -  git init   - to create git repo in project
   6. run:  git status  - to check the uncommitted files
   7. git add .  : to add files to stagging area



*/
