/* Azure Devops cloud

# Azure Devops claud servers take care of our Project execution
It HAs advantages that  we can utilize by defining diff configurations in playwright.yml 
file to create cicd pipeline

1. We can make faster test execution by running tests parallely on different workers
2. It Automatically setups the node configurations, 
3. It automatically download dependancies, browsers and provides inbuilt playwright 
   environment in azure server virtual machines, 
4. setup and login to azure cloud
5. execute test on azure cloud
6. Generates the final consolidated report

Steps->
1.create the free account in microsoft azure by providing all info
2. login to azure acc goto dashboard click on 3 dots -> create resource-> search for 'playwright workspace' -> click
-> provide all info -> create ->goto azure dashboard-> click 3dots ->az login get started -> 

follow the steps to integrate our local workspace to to azure workspace as follows

 get the ids from azure account
object id - cc6a965c-e80a-4d78-8dc5-b3220faf566f
Storage account id - pwstrgrrde857

run following Cmds in PW terminal to 

 1. install PW service package - npm init @azure/playwright@latest 
  when we run above cmd in project playwright.service.config.js file is generated by using which 
  we do execution in azure cloud

 2. download and install - azure cli
 
run following cmds to setup local workspace to azure workspace
 3. Login to azure using azure cli  -  az login  : when run this cmd browser windo open to select azure acc
 
4. $env:PLAYWRIGHT_SERVICE_URL="wss://eastus.api.playwright.microsoft.com/playwrightworkspaces/68cec135-967f-41a0-9c72-1be0d04c01c4/browsers"

5  to Get the resource ID and store it in a variable run cmd
$storageId = az storage account show --name pwstrgrrde857 --resource-group rrd --query id -o tsv

# 6. Run the role assignment using the variable

az role assignment create `
   --assignee "cc6a965c-e80a-4d78-8dc5-b3220faf566f" `
   --role "Storage Blob Data Contributor" `
   --scope \$storageId

   7.use cmd to cloud execution - npx playwright test --config=playwright.service.config.ts --workers=20

   8. When we run above 7th cmd then execution will happen in azure cloud. 
    By default playwright run tests on parallely on diff workers we have define
   we can login to azureaccount goto testsrun- we can see all info like logs ,reports so
     we can shre the that browser link of report to team  

   9. we can also configure above cmd in .yml file and schedule the job/execution in azure cloud.
   so we can see all info by login to azure acc.


   ***********Push Local code to Github repo for cicd demo************

   1. Login to Github acc
   2. create new Repo
   3. Downlod and install git in local system
   4. Goto project derectory and open cmd prompt
   5. run cmd -  git init   - to create git repo in project
   6. run:  git status  - to check the uncommitted files
   7. git add .  : to add files to stagging area
   8. git commit -m "msg"  : to commit changes to local repo
   9. add the origine : git remote add origin https://github.com/dhaneshrajedbm/PlaywrightWorkspace_Udemy.git
   10. git push -u origin master  : for first time code push and provide authentication



*******Playwrite Github Actions and configure .yml file to start excution in azure cloud when there is code push done in github****************

goto officil wesite - https://playwright.dev/docs/ci-intro

when we integrete github with project workspace then in that ".github" folder is created
which by default contains the "plywright.yml" file -> in which we can define diff configurations in it to 
create CICD pipline

on is the event that tell the when to trigger the job . in this case there is mention 'push' and 'pull req'  means
when the code push/pull Req happens to  main/master branch then trigger the job means CICD pipeline
automatically start execution in the azure cloud

job is nothing but the set of actions which we do when trigger job execution 

******connecting Github actions pipeline to azure cloud***************

we can setup the configurations in .yml file to automatically integrate the our playwright workspace to 
azure cloud 
for that we have to create 1 service account based on azure subscription id.for that run below cmd
Subscription id - c411ae04-a2cc-4a2e-8f49-9e6473752c68

az ad sp create-for-rbac --name "github-playwright" --role "Contributor" --scopes "/subscriptions/c411ae04-a2cc-4a2e-8f49-9e6473752c68/resourceGroups/RRD" --json-auth

when run above cmd it generates client id clienr secret details from that we connect github actions to cloud
To get the service account 
steps-
1. copy generated details
2. goto github acc->setting->secret and variables->actions->create secret repo->paste the details
  i.e azure credentials -> then configure that azure cred in playwright.yml file for that 
  just add below code in .yml file

  - name : Azure Login
    uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURECREDENTIALS }}


# also define cmd in yml file for azure cloud execution - npx playwright test --config=playwright.service.config.ts --workers=4

# also we have set below  browser endpoint where all  our execution is happen in cloud  so we can configure it in yml file
$env:PLAYWRIGHT_SERVICE_URL="wss://eastus.api.playwright.microsoft.com/playwrightworkspaces/68cec135-967f-41a0-9c72-1be0d04c01c4/browsers"
steps->
goto github acc->setting->secret and variables->actions->variables tab->new repo variables-> give name as -PLAYWRIGHT_SERVICE_URL and value as url
then  add below line in yml file
env:
   PLAYWRIGHT_SERVICE_URL: ${{ vars.PLAYWRIGHT_SERVICE_URL }}

   # Then we have to run below cmd in playwright terminal ->
   az role assignment create --assignee (az ad sp list --display-name "github-playwright" --query "[0].appId" -o tsv) --role "Storage Blob Data Contributor" --scope (az storage account show --name pwstrgrrde857 --resource-group RRD --query id -o tsv)

############# CICD Pipeline with playwright.yml file ##########################################

we have configured playwright.yml file in such a way that it automatically integrate with azure cloud and when there is new code 
is push or raise pull request to github repo then automatically CICD pipeline triggers and 
start execution in azure cloud.

we have configured yml file as follows so it automatically
1.set a job
2. do the node setups
3. install dependancies
4. setup  and login to azure cloud 
5. Run playwright tests with the playwright.service.config file
6. generate reports and which we can share with team

// Now we are configure .yml file insuch a way that when new PR is created to merge the 
// code in remote repo then trigger the cicd pipeline

1. in yml file set - 
on:
  pull_request:
    branches: [ main, master ] 

1. git branch Dhanesh  : create new branch
2. do code change and add and commit them
3. git push origin Dhanesh    : push changes to local branch
4. Raise the PR 
5.  we can also do setting like without passing all excution checks the mergre pull request button is not enabled
6. for that we have to setrules in github accordingly.


name: Playwright Tests
on:
  push:
    branches: [ main, master,septCut ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest       // All our code is clone to Ubuntu machine and there 
                                 //     will happen the exution by running the below cmds 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name : Azure Login                 // Azure setup and login
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURECREDENTIALS }}

    - name: Run Playwright tests      //cmd to run the actal tests.workrrs=4 means  4 tests 
                                      // are run parallely  on each virtual machines
      env:
      PLAYWRIGHT_SERVICE_URL: ${{ vars.PLAYWRIGHT_SERVICE_URL }}

      run: npx playwright test --config=playwright.service.config.ts --workers=4  

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30







        run following cmds to setup local workspace to azure workspace

objected - cc6a965c-e80a-4d78-8dc5-b3220faf566f
Storage account - pwstrgrrde857

1.az login


2. $env:PLAYWRIGHT_SERVICE_URL="wss://eastus.api.playwright.microsoft.com/playwrightworkspaces/68cec135-967f-41a0-9c72-1be0d04c01c4/browsers"



# 3. Get the resource ID and store it in a variable
$storageId = az storage account show --name pwstrgrrde857 --resource-group rrd --query id -o tsv

# 4. Run the role assignment using the variable
az role assignment create `
   --assignee "cc6a965c-e80a-4d78-8dc5-b3220faf566f" `
   --role "Storage Blob Data Contributor" `
   --scope \$storageId






To create the service account 

Subscription id - c411ae04-a2cc-4a2e-8f49-9e6473752c68

az ad sp create-for-rbac --name "github-playwright" --role "Contributor" --scopes "/subscriptions/c411ae04-a2cc-4a2e-8f49-9e6473752c68/resourceGroups/RRD" --json-auth


after create service acc run below cmd

az role assignment create \
--assignee "$(az ad sp list --display-name 'github-playwright' --query '[0].appId' -o tsv)" \
--role "Storage Blob Data Contributor" \
--scope "$(az storage account show --name pwstrgrrde857 --resource-group RRD --query id -o tsv)"


*/
