//Auther : Dhanesh
// Code generated by giving cmd  - @workspace create a new file and add new playwright code make http get call


import { test, expect } from '@playwright/test';

test('@APITEST GET request returns a post', async ({ request }) => {
    const response = await request.get('https://jsonplaceholder.typicode.com/posts/1');

    expect(response.status()).toBe(200);
    expectxpect(response.status()).toBe(200);

    //cmd - write all assertions to verify the response data

    const post = await response.json();
    expect(post.id).toBe(1);
    expect(post).toHaveProperty('title');

    expect(post).toHaveLength(100);

   // const post = await response.json();

    expect(post[0]).toEqual({
        userId: 1,
        id: 1,
        title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
        body: 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto',
    });
});

//Open new Chat Editor(click upper + sign select new Chat Editor )-> select file in which we have to edit code (click bottom + sign btn to select ) give below cmd to edit the code in that file

//write another test for http get call and verify status code, response time, headers, response body data and data count.


test('@APITEST GET posts verifies response details', async ({ request }) => {
    const startTime = Date.now();
    const response = await request.get('https://jsonplaceholder.typicode.com/posts');
    const responseTime = Date.now() - startTime;

    expect(response.status()).toBe(200);
    expect(responseTime).toBeLessThan(5000);

    const headers = response.headers();
    expect(headers['content-type']).toContain('application/json');

    const posts = await response.json();
    expect(posts).toHaveLength(100);
    expect(posts[0]).toMatchObject({
        userId: 1,
        id: 1,
        title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
    });
});


/*
cmd = @terminal  how to run specific test with specific tag in headed mode 
op= npx playwright test {test_file} --grep "{tag_name}" --headed

cmd -- generate manual test cases for selected file

I’ll review the current Playwright spec and turn it into a concise set of manual test cases that match the actual behaviors in this file.

## Manual test cases for `Test12.spec.js`

These are manual test cases derived from the two API checks in the file: one for a single post and one for the full posts list.

### 1) TC-API-01: GET single post returns successful response and valid data
- Objective: Verify that a valid request to fetch one post returns the correct HTTP status and expected payload.
- Preconditions:
  - Internet access is available.
  - The target API is reachable: https://jsonplaceholder.typicode.com/posts/1
- Steps:
  1. Open Postman, curl, or a browser.
  2. Send a GET request to https://jsonplaceholder.typicode.com/posts/1.
  3. Capture the response status, headers, and body.
- Expected results:
  - HTTP status is 200.
  - Response content type includes application/json.
  - Response body is valid JSON.
  - Returned object has id = 1.
  - The object contains a title property.
  - Title is not empty.
  - The returned body matches the expected sample structure for post 1.

---

### 2) TC-API-02: GET single post contains the expected post structure
- Objective: Validate that the returned object contains the correct fields and values.
- Preconditions:
  - TC-API-01 is successful.
- Steps:
  1. Send GET request to https://jsonplaceholder.typicode.com/posts/1.
  2. Inspect the JSON object.
- Expected results:
  - The JSON has keys such as userId, id, title, and body.
  - userId equals 1.
  - id equals 1.
  - title matches the known expected value.
  - body contains the expected content for the first post.
  - The object is not null and is parsed correctly as JSON.

---

### 3) TC-API-03: GET all posts returns success and correct list size
- Objective: Verify that the posts collection endpoint returns a valid list.
- Preconditions:
  - Internet access is available.
  - The target API is reachable: https://jsonplaceholder.typicode.com/posts
- Steps:
  1. Send a GET request to https://jsonplaceholder.typicode.com/posts.
  2. Record the HTTP status, response time, headers, and total list count.
- Expected results:
  - HTTP status is 200.
  - Response completes within 5 seconds.
  - Content type includes application/json.
  - Response is an array of posts.
  - Array length is 100.
  - The first item is a valid post with id = 1.

---

### 4) TC-API-04: GET all posts validates response time and headers
- Objective: Confirm performance and header correctness for the posts list API.
- Preconditions:
  - API is reachable.
- Steps:
  1. Measure the time before and after sending the GET request.
  2. Check response headers.
  3. Review the returned content type and structure.
- Expected results:
  - Response time is less than 5000 ms.
  - Content-Type contains application/json.
  - The response includes expected headers such as content-type.
  - The payload is not empty and is valid JSON.

---

### 5) TC-API-05: GET all posts validates first record content
- Objective: Ensure the first element in the response matches the known dataset.
- Preconditions:
  - TC-API-03 is successful.
- Steps:
  1. Send GET request to https://jsonplaceholder.typicode.com/posts.
  2. Read the first element of the array.
- Expected results:
  - userId = 1
  - id = 1
  - title matches the expected text for the first post
  - The first post is a valid object and matches the known sample data

---

### Optional negative scenario
- TC-API-06: Nonexistent post ID
  - Send GET to https://jsonplaceholder.typicode.com/posts/9999
  - Expected: If the API returns a 404, the application should handle it gracefully and not treat it as a successful record fetch.

If you want, I can also convert these into a cleaner QA format with fields like ID, priority, severity, preconditions, test data, and expected result in a table.



*/